name: "Generate report"
on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/checkout@v3
      - name: Build with Gradle
        run: |
          ./gradlew shadowJar
      - name: Rebuild README.md
        run: |
          cat RUNNING.md > README.md
          java -jar build/libs/module-checker-0.1-all.jar -m >> README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Update README with latest report
          commit_user_name: micronaut-build
